steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Run unit tests
  - name: python
    entrypoint: python
    args: ["-m", "pytest", "--junitxml=test_log.xml"] 

  ## TODO: Upload test file to artifact registry

  # Deploy to Cloud Functions
  - name: google/cloud-sdk
    args: ['gcloud', 'functions', 'deploy', 'helloworld', 
           '--runtime=python38', '--trigger-http', 
           '--allow-unauthenticated', '--entry-point=hello_world']
